% Microsoft Sql Server / PurgeDatabase
% v1.3.0.20220113.beta
%       首次加入
function ret = PurgeDatabase(obj, varargin)
% 确定端口
conn = obj.SelectConn(obj.db_default);

% 确定前缀
prefix = cell(length(varargin), 1);
for i = 1 : length(varargin)
    prefix{i} = [varargin{i}, '%'];
end

% 生成语句
sql = repmat(' name LIKE ''%s'' OR', 1,  length(varargin));
sql(end - 1 : end) = [];
sql = sprintf('DECLARE dbs CURSOR FAST_FORWARD FOR SELECT name FROM sysdatabases WHERE %s;', sql);
sql = sprintf(sql, prefix{:});

sql = sprintf( ...
    " BEGIN " ...
    + "    %s " ...
    + "    DECLARE @db varchar(128)" ...
    + "    OPEN dbs" ...
    + "    WHILE 1=1" ...
    + "    BEGIN " ...
    + "        FETCH NEXT FROM dbs INTO @db" ...
    + "        if(@@fetch_status!=0) BREAK" ...
    + "        EXEC('DROP DATABASE [' + @db + ']')" ...
    + "    END " ...
    + "    CLOSE dbs " ...
    + "    DEALLOCATE dbs " ...
    + " END", ...
    sql);
cr = exec(conn, sql);

% return
if (strcmpi(cr.Message, '该语句没有返回结果集。'))
    ret = true;
else
    ret = false;
end
end