% Microsoft Sql Server / SaveChainOption
% v1.3.0.20220113.beta
%       首次添加
function ret = SaveChainOption(obj, var, exc, instrus)
% 数据库准备
if (isempty(instrus))
    ret = false;
    return;
end
db = obj.db_instru;
conn = obj.SelectConn(db);

% 表准备
tb = BaseClass.Database.Database.GetTableName(EnumType.Product.Option, var, EnumType.Exchange.ToEnum(exc));
if (~obj.CheckTable(db, tb))
    obj.CreateTable(conn, db, tb, instrus);
end

% 生成sql
fprintf("Inserting option chain ""%s"", please wait ...\r", tb);
sql = string();
for i = 1 : size(instrus, 1)
    this = instrus(i, :);
    head = sprintf("IF EXISTS (SELECT * FROM [%s] WHERE [SYMBOL] = '%s') UPDATE [%s] SET [SEC_NAME] = '%s', [EXCHANGE] = '%s', [VARIETY] = '%s', [UD_SYMBOL] = '%s', [UD_PRODUCT] = '%s', [UD_EXCHANGE] = '%s', [CALL_OR_PUT] = '%s', [STRIKE_TYPE] = '%s', [STRIKE] = %f, [SIZE] = %f, [TICK_SIZE] = %f, [DLMONTH] = %i, [START_TRADE_DATE] = '%s', [END_TRADE_DATE] = '%s', [SETTLE_MODE] = '%s', [LAST_UPDATE_DATE] = '%s' WHERE [SYMBOL] = '%s'", ...
        tb, ...
        this.SYMBOL{:}, ...
        tb, ...
        this.SEC_NAME{:}, ...
        this.EXCHANGE{:}, ...
        this.VARIETY{:}, ...
        this.UD_SYMBOL{:}, ...
        this.UD_PRODUCT{:}, ...
        this.UD_EXCHANGE{:}, ...
        this.CALL_OR_PUT{:}, ...
        this.STRIKE_TYPE{:}, ...
        this.STRIKE, ...
        this.SIZE, ...
        this.TICK_SIZE, ...
        this.DLMONTH, ...
        this.START_TRADE_DATE{:}, ...
        this.END_TRADE_DATE{:}, ...
        this.SETTLE_MODE{:}, ...
        this.LAST_UPDATE_DATE{:}, ...
        this.SYMBOL{:} ...
        );

    tail = sprintf(" ELSE INSERT [%s]([SYMBOL], [SEC_NAME], [EXCHANGE], [VARIETY], [UD_SYMBOL], [UD_PRODUCT], [UD_EXCHANGE], [CALL_OR_PUT], [STRIKE_TYPE], [STRIKE], [SIZE], [TICK_SIZE], [DLMONTH], [START_TRADE_DATE], [END_TRADE_DATE], [SETTLE_MODE], [LAST_UPDATE_DATE]) VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', %f, %f, %f, %i, '%s', '%s', '%s', '%s')", ...
        tb, ...
        this.SYMBOL{:}, ...
        this.SEC_NAME{:}, ...
        this.EXCHANGE{:}, ...
        this.VARIETY{:}, ...
        this.UD_SYMBOL{:}, ...
        this.UD_PRODUCT{:}, ...
        this.UD_EXCHANGE{:}, ...
        this.CALL_OR_PUT{:}, ...
        this.STRIKE_TYPE{:}, ...
        this.STRIKE, ...
        this.SIZE, ...
        this.TICK_SIZE, ...
        this.DLMONTH, ...
        this.START_TRADE_DATE{:}, ...
        this.END_TRADE_DATE{:}, ...
        this.SETTLE_MODE{:}, ...
        this.LAST_UPDATE_DATE{:} ...
        );

    sql = sql + head + tail;
end

% 入库
exec(conn, sql);
ret = true;
end