% 合约入库
function ret = MarketData2Database(opt, db_)

% 建库检查

% 建表检查

% 


%             % 入库
%             % 建表
%             sql_string = ['CREATE TABLE [', name_table, '](', ...
%                 '[Date] [INT] NULL, ', ...
%                 '[Datenum] [INT] NOT NULL, ', ...
%                 '[OPEN] [numeric](18, 4) NULL, ', ...
%                 '[HIGH] [numeric](18, 4) NULL, ', ...
%                 '[LOW] [numeric](18, 4) NULL, ', ...
%                 '[CLOSE] [numeric](18, 4) NULL, ', ...
%                 '[VOLUME] [numeric](18, 4) NULL, ', ...
%                 '[AMT] [numeric](18, 4) NULL, ', ...
%                 '[IO] [numeric](18, 4) NULL, ', ...
%                 '[PRE_SETTLE] [numeric](18, 4) NULL, ', ...
%                 '[SETTLE] [numeric](18, 4) NULL, ', ...
%                 '[DELTA] [numeric](18, 4) NULL, ', ...
%                 '[GAMMA] [numeric](18, 4) NULL, ', ...
%                 '[THETA] [numeric](18, 4) NULL, ', ...
%                 '[VEGA] [numeric](18, 4) NULL, ', ...
%                 '[RHO] [numeric](18, 4) NULL, ', ...
%                 '[Vol_His_30D] [numeric](18, 4) NULL, ', ...
%                 '[Vol_His] [numeric](18, 4) NULL, ', ...
%                 '[Vol_His_90D] [numeric](18, 4) NULL, ', ...
%                 '[IV] [numeric](18, 4) NULL, ', ...
%                 '[ptmday] [INT] NULL, ', ...
%                 '[ptmtradeday] [INT] NULL ', ...
%                 ')ON [PRIMARY]'];
%             exec(api_local.conn, sql_string);
%             
%             % 删除
%             sql_string = ['DELETE FROM [', obj.name_database, '].[DBO].[', name_table, '] WHERE Datenum >= ', num2str(insert(1, 2))];
%             exec(api_local.conn, sql_string);
%             
%             % 插入
%             column = {'[Date]', '[Datenum]', '[OPEN]', '[HIGH]', '[LOW]', '[CLOSE]', '[VOLUME]', '[AMT]', ...
%                 '[IO]', '[PRE_SETTLE]', '[SETTLE]', ...
%                 '[DELTA]', '[GAMMA]', '[THETA]', '[VEGA]', '[RHO]', ...
%                 '[Vol_His_30D]', '[Vol_His]', '[Vol_His_90D]', '[IV]', '[ptmday]', '[ptmtradeday]'};
%             fastinsert(api_local.conn, ['[', name_table, ']'], column, num2cell(insert));

end


