% Utility / SampleOption
% v1.3.0.20220113.beta
%      1.First Commit
function option = SampleOption(pdt, var, exc, inv_, info)
switch var
    case {'159919', '510050', '510300'}
        if (~isempty(info))
            option = BaseClass.Asset.Asset.Selector(pdt, var, exc, ...
                info.SYMBOL{:}, ...
                info.SEC_NAME{:}, ...
                inv_, ...
                info.SIZE, ...
                EnumType.CallOrPut.ToEnum(info.CALL_OR_PUT{:}), ...
                info.STRIKE, ...
                info.START_TRADE_DATE{:}, ...
                info.END_TRADE_DATE{:}...
                );
        else
            option = BaseClass.Asset.Asset.Selector(pdt, var, exc, ...
                'sample', ...
                'sample', ...
                inv_, ...
                10000, ...
                EnumType.CallOrPut.Call, ...
                888, ...
                datestr(now()), ...
                datestr(now())...
                );
        end

    otherwise
        error('Unsupported variety for option sample, please check !');
end
end
