% Utility / SampleOption
% v1.3.0.20220113.beta
%      1.First Commit
function option = SampleOption(pdt_, var_, exc_, inv_)
switch var_
    case {'159919', '510050', '510300'}
        option = BaseClass.Asset.Asset.Selector(pdt_, var_, exc_, ...
            'sample', ...
            'sample', ...
            inv_, ...
            10000, ...
            EnumType.CallOrPut.Call, ...
            888, ...
            datestr(now()), ...
            datestr(now())...
            );

    otherwise
        error('Unsupported variety for option sample, please check !');
end
end